AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Prints Hello World
Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handle
      Runtime: python2.7
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
